const text = (name, label, options = {}) => ({ name, label, type: "text", ...options });
const textarea = (name, label, options = {}) => ({ name, label, type: "textarea", ...options });
const number = (name, label, options = {}) => ({ name, label, type: "number", ...options });
const image = (name, label, options = {}) => ({ name, label, type: "image", ...options });
const serviceSelect = (required = true) => ({
  name: "serviceId",
  label: "Service",
  type: "select",
  required,
  optionsResource: "services",
  optionLabelKey: "titre",
});
const sousServiceSelect = (required = true) => ({
  name: "sousServiceId",
  label: "Sous-service",
  type: "select",
  required,
  optionsResource: "sous-services",
  optionLabelKey: "titre",
});

export const crudConfigs = {
  etiquettes: {
    resource: "etiquettes",
    route: "etiquettes",
    title: "Etiquettes",
    singular: "etiquette",
    description: "Gerez les etiquettes utilisees pour qualifier les services.",
    fields: [text("nom", "Nom", { required: true })],
    columns: [
      { key: "id", header: "ID" },
      { key: "nom", header: "Nom" },
    ],
    searchFields: ["nom"],
  },
  pays: {
    resource: "pays",
    route: "pays",
    title: "Pays",
    singular: "pays",
    description: "Gerez les zones de presence affichees sur le site.",
    fields: [
      text("nom", "Nom", { required: true }),
      text("codePays", "Code pays"),
      text("ville", "Ville"),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "nom", header: "Nom" },
      { key: "codePays", header: "Code" },
      { key: "ville", header: "Ville" },
    ],
    searchFields: ["nom", "codePays", "ville"],
  },
  chiffresCles: {
    resource: "chiffres-cles",
    route: "chiffres-cles",
    title: "Chiffres cles",
    singular: "chiffre cle",
    description: "Gerez les indicateurs chiffres visibles sur la vitrine.",
    fields: [
      text("valeur", "Valeur", { required: true }),
      text("libelle", "Libelle", { required: true }),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "valeur", header: "Valeur" },
      { key: "libelle", header: "Libelle" },
    ],
    searchFields: ["valeur", "libelle"],
  },
  services: {
    resource: "services",
    route: "services",
    title: "Services",
    singular: "service",
    description: "Gerez les offres principales HWC.",
    fields: [
      text("titre", "Titre", { required: true }),
      text("accroche", "Accroche"),
      textarea("description", "Description", { required: true }),
      text("icone", "Icone"),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "titre", header: "Titre" },
      { key: "accroche", header: "Accroche" },
      { key: "icone", header: "Icone" },
    ],
    searchFields: ["titre", "accroche", "description", "icone"],
  },
  sousServices: {
    resource: "sous-services",
    route: "sous-services",
    title: "Sous-services",
    singular: "sous-service",
    description: "Gerez les pages detaillees rattachees aux services.",
    fields: [
      text("titre", "Titre", { required: true }),
      text("accroche", "Accroche"),
      textarea("description", "Description"),
      textarea("descriptionComplete", "Description complete"),
      text("icone", "Icone"),
      serviceSelect(),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "titre", header: "Titre" },
      { key: "serviceTitre", header: "Service" },
      { key: "icone", header: "Icone" },
    ],
    searchFields: ["titre", "accroche", "description", "serviceTitre"],
  },
  clientsConfiance: {
    resource: "clients-confiance",
    route: "clients-confiance",
    title: "Clients confiance",
    singular: "client",
    description: "Gerez les logos clients affiches comme preuves de confiance.",
    fields: [text("nom", "Nom", { required: true }), image("logoUrl", "Logo")],
    columns: [
      { key: "id", header: "ID" },
      { key: "nom", header: "Nom" },
      { key: "logoUrl", header: "Logo URL" },
    ],
    searchFields: ["nom", "logoUrl"],
  },
  temoignages: {
    resource: "temoignages",
    route: "temoignages",
    title: "Temoignages",
    singular: "temoignage",
    description: "Gerez les temoignages et references sociales.",
    fields: [
      text("nom", "Nom", { required: true }),
      image("logoUrl", "Logo"),
      text("type", "Type"),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "nom", header: "Nom" },
      { key: "type", header: "Type" },
      { key: "logoUrl", header: "Logo URL" },
    ],
    searchFields: ["nom", "type", "logoUrl"],
  },
  certifications: {
    resource: "certifications",
    route: "certifications",
    title: "Certifications",
    singular: "certification",
    description: "Gerez les certifications et labels affiches sur le site.",
    fields: [
      text("nom", "Nom", { required: true }),
      image("logoUrl", "Logo"),
      text("type", "Type"),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "nom", header: "Nom" },
      { key: "type", header: "Type" },
      { key: "logoUrl", header: "Logo URL" },
    ],
    searchFields: ["nom", "type", "logoUrl"],
  },
  serviceFonctionnalites: {
    resource: "service-fonctionnalites",
    route: "service-fonctionnalites",
    title: "Fonctionnalites services",
    singular: "fonctionnalite service",
    description: "Gerez les fonctionnalites rattachees aux services.",
    fields: [textarea("contenu", "Contenu", { required: true }), serviceSelect()],
    columns: [
      { key: "id", header: "ID" },
      { key: "contenu", header: "Contenu" },
      { key: "serviceId", header: "Service ID" },
    ],
    searchFields: ["contenu", "serviceId"],
  },
  serviceImages: {
    resource: "service-images",
    route: "service-images",
    title: "Images services",
    singular: "image service",
    description: "Gerez les images rattachees aux services.",
    fields: [image("imageUrl", "Image", { required: true }), serviceSelect()],
    columns: [
      { key: "id", header: "ID" },
      { key: "imageUrl", header: "Image URL" },
      { key: "serviceId", header: "Service ID" },
    ],
    searchFields: ["imageUrl", "serviceId"],
  },
  sousServiceFonctionnalites: {
    resource: "sous-service-fonctionnalites",
    route: "sous-service-fonctionnalites",
    title: "Fonctionnalites sous-services",
    singular: "fonctionnalite sous-service",
    description: "Gerez les fonctionnalites rattachees aux sous-services.",
    fields: [textarea("contenu", "Contenu", { required: true }), sousServiceSelect()],
    columns: [
      { key: "id", header: "ID" },
      { key: "contenu", header: "Contenu" },
      { key: "sousServiceId", header: "Sous-service ID" },
    ],
    searchFields: ["contenu", "sousServiceId"],
  },
  sousServiceAvantages: {
    resource: "sous-service-avantages",
    route: "sous-service-avantages",
    title: "Avantages sous-services",
    singular: "avantage sous-service",
    description: "Gerez les avantages rattaches aux sous-services.",
    fields: [
      text("titre", "Titre", { required: true }),
      textarea("description", "Description"),
      sousServiceSelect(),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "titre", header: "Titre" },
      { key: "description", header: "Description" },
      { key: "sousServiceId", header: "Sous-service ID" },
    ],
    searchFields: ["titre", "description", "sousServiceId"],
  },
  sousServiceEtapes: {
    resource: "sous-service-etapes",
    route: "sous-service-etapes",
    title: "Etapes sous-services",
    singular: "etape sous-service",
    description: "Gerez les etapes des parcours sous-services.",
    fields: [
      number("numero", "Numero", { required: true }),
      text("titre", "Titre", { required: true }),
      textarea("description", "Description"),
      sousServiceSelect(),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "numero", header: "Numero" },
      { key: "titre", header: "Titre" },
      { key: "sousServiceId", header: "Sous-service ID" },
    ],
    searchFields: ["numero", "titre", "description", "sousServiceId"],
  },
  sousServiceFaqs: {
    resource: "sous-service-faqs",
    route: "sous-service-faqs",
    title: "FAQs sous-services",
    singular: "FAQ sous-service",
    description: "Gerez les questions frequentes rattachees aux sous-services.",
    fields: [
      textarea("question", "Question", { required: true }),
      textarea("reponse", "Reponse", { required: true }),
      sousServiceSelect(),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "question", header: "Question" },
      { key: "reponse", header: "Reponse" },
      { key: "sousServiceId", header: "Sous-service ID" },
    ],
    searchFields: ["question", "reponse", "sousServiceId"],
  },
  accompagnements: {
    resource: "accompagnements",
    route: "accompagnements",
    title: "Accompagnements",
    singular: "accompagnement",
    description: "Gerez les blocs d'accompagnement des sous-services.",
    fields: [
      text("titre", "Titre", { required: true }),
      text("accroche", "Accroche"),
      textarea("description1", "Description 1"),
      textarea("description2", "Description 2"),
      sousServiceSelect(),
    ],
    columns: [
      { key: "id", header: "ID" },
      { key: "titre", header: "Titre" },
      { key: "accroche", header: "Accroche" },
      { key: "sousServiceId", header: "Sous-service ID" },
    ],
    searchFields: ["titre", "accroche", "description1", "description2", "sousServiceId"],
  },
  demandesContact: {
    resource: "demandes-contact",
    route: "demandes-contact",
    title: "Demandes contact",
    singular: "demande contact",
    description: "Consultez et supprimez les demandes de contact recues.",
    readOnly: true,
    fields: [],
    columns: [
      { key: "id", header: "ID" },
      { key: "email", header: "Email" },
    ],
    searchFields: ["email"],
  },
};
